name = "personal-hub-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "personal-hub-db"
database_id = "local"
migrations_dir = "../../migrations"

[env.production]
name = "personal-hub-api-production"
[[env.production.d1_databases]]
binding = "DB"
database_name = "personal-hub-db-production"
database_id = "fc40f3ff-0d1c-4e60-8826-5d109f7af307"
migrations_dir = "../../migrations"

[env.staging]
name = "personal-hub-api-staging"
[[env.staging.d1_databases]]
binding = "DB"
database_name = "personal-hub-db-staging"
database_id = "160bf9aa-485d-41b2-82f0-4e3e93c50903"
migrations_dir = "../../migrations"