name = "personal-hub-backend-staging"
main = "src/index.ts"
compatibility_date = "2025-01-19"

# Staging environment configuration
[env.staging]
[[env.staging.d1_databases]]
binding = "DB"
database_name = "personal-hub-staging"
database_id = "STAGING_DATABASE_ID_PLACEHOLDER" # Replace with actual ID before deployment

[env.staging.vars]
ENVIRONMENT = "staging"