-- Add PENDING status to pomodoro_sessions
-- Since the production table was created without a CHECK constraint (from migration 0000),
-- and Cloudflare D1 has limitations with complex migrations,
-- we'll ensure the application code handles the new PENDING status value correctly.
-- No schema changes are needed as the status column accepts any TEXT value.